/********************************************************************
* b2ddsj_evt_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error b2ddsj_evt_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableb2ddsj_evt_dict();
extern void G__cpp_setup_inheritanceb2ddsj_evt_dict();
extern void G__cpp_setup_typetableb2ddsj_evt_dict();
extern void G__cpp_setup_memvarb2ddsj_evt_dict();
extern void G__cpp_setup_globalb2ddsj_evt_dict();
extern void G__cpp_setup_memfuncb2ddsj_evt_dict();
extern void G__cpp_setup_funcb2ddsj_evt_dict();
extern void G__set_cpp_environmentb2ddsj_evt_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "b2ddsj_evt.h"
#include "b2ddsj_mcevt.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__b2ddsj_evt_dictLN_TClass;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_TBuffer;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_TMemberInspector;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_TObject;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_EvtInfo;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_EvtShape;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_GammaInfo;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_GenHepEvt;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_GenParticleInfo;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_IPBoost;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_Ks0Info;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_Pi0Info;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_TrackInfo;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_b2ddsj_evt;
extern G__linked_taginfo G__b2ddsj_evt_dictLN_b2ddsj_mcevt;

/* STUB derived class for protected member access */
