//
// File generated by rootcint at Fri Mar 18 12:13:13 2016

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "b2ddsj_evt_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void b2ddsj_evt_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_b2ddsj_evt(void *p = 0);
   static void *newArray_b2ddsj_evt(Long_t size, void *p);
   static void delete_b2ddsj_evt(void *p);
   static void deleteArray_b2ddsj_evt(void *p);
   static void destruct_b2ddsj_evt(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::b2ddsj_evt*)
   {
      ::b2ddsj_evt *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::b2ddsj_evt >(0);
      static ::ROOT::TGenericClassInfo 
         instance("b2ddsj_evt", ::b2ddsj_evt::Class_Version(), "../include/b2ddsj_evt.h", 15,
                  typeid(::b2ddsj_evt), DefineBehavior(ptr, ptr),
                  &::b2ddsj_evt::Dictionary, isa_proxy, 0,
                  sizeof(::b2ddsj_evt) );
      instance.SetNew(&new_b2ddsj_evt);
      instance.SetNewArray(&newArray_b2ddsj_evt);
      instance.SetDelete(&delete_b2ddsj_evt);
      instance.SetDeleteArray(&deleteArray_b2ddsj_evt);
      instance.SetDestructor(&destruct_b2ddsj_evt);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::b2ddsj_evt*)
   {
      return GenerateInitInstanceLocal((::b2ddsj_evt*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::b2ddsj_evt*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void b2ddsj_mcevt_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_b2ddsj_mcevt(void *p = 0);
   static void *newArray_b2ddsj_mcevt(Long_t size, void *p);
   static void delete_b2ddsj_mcevt(void *p);
   static void deleteArray_b2ddsj_mcevt(void *p);
   static void destruct_b2ddsj_mcevt(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::b2ddsj_mcevt*)
   {
      ::b2ddsj_mcevt *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::b2ddsj_mcevt >(0);
      static ::ROOT::TGenericClassInfo 
         instance("b2ddsj_mcevt", ::b2ddsj_mcevt::Class_Version(), "../include/b2ddsj_mcevt.h", 13,
                  typeid(::b2ddsj_mcevt), DefineBehavior(ptr, ptr),
                  &::b2ddsj_mcevt::Dictionary, isa_proxy, 0,
                  sizeof(::b2ddsj_mcevt) );
      instance.SetNew(&new_b2ddsj_mcevt);
      instance.SetNewArray(&newArray_b2ddsj_mcevt);
      instance.SetDelete(&delete_b2ddsj_mcevt);
      instance.SetDeleteArray(&deleteArray_b2ddsj_mcevt);
      instance.SetDestructor(&destruct_b2ddsj_mcevt);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::b2ddsj_mcevt*)
   {
      return GenerateInitInstanceLocal((::b2ddsj_mcevt*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::b2ddsj_mcevt*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *b2ddsj_evt::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *b2ddsj_evt::Class_Name()
{
   return "b2ddsj_evt";
}

//______________________________________________________________________________
const char *b2ddsj_evt::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::b2ddsj_evt*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int b2ddsj_evt::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::b2ddsj_evt*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void b2ddsj_evt::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::b2ddsj_evt*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *b2ddsj_evt::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::b2ddsj_evt*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *b2ddsj_mcevt::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *b2ddsj_mcevt::Class_Name()
{
   return "b2ddsj_mcevt";
}

//______________________________________________________________________________
const char *b2ddsj_mcevt::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::b2ddsj_mcevt*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int b2ddsj_mcevt::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::b2ddsj_mcevt*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void b2ddsj_mcevt::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::b2ddsj_mcevt*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *b2ddsj_mcevt::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::b2ddsj_mcevt*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void b2ddsj_evt::Streamer(TBuffer &R__b)
{
   // Stream an object of class b2ddsj_evt.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      info.Streamer(R__b);
      R__b >> de;
      R__b >> mbc;
      R__b >> costhBcms;
      shape.Streamer(R__b);
      R__b >> mode_b;
      R__b >> mode_d;
      R__b >> mode_ds;
      R__b >> mode_dsj;
      R__b >> flvb;
      R__b >> md;
      R__b >> mdsj;
      R__b >> dmdst;
      R__b >> mds;
      R__b >> dmdsst;
      R__b >> mvec;
      R__b.ReadStaticArray((double*)pvec);
      R__b >> cos_hel_dsj;
      R__b >> cos_hel_vec;
      R__b >> cos_hel_b;
      gam_dsj.Streamer(R__b);
      gam_dsst.Streamer(R__b);
      pi0_dst.Streamer(R__b);
      pi0_dsj.Streamer(R__b);
      pi_dst.Streamer(R__b);
      pip_dsj.Streamer(R__b);
      pim_dsj.Streamer(R__b);
      k_d.Streamer(R__b);
      pi_d.Streamer(R__b);
      pi2_d.Streamer(R__b);
      h_ds.Streamer(R__b);
      ks_ds.Streamer(R__b);
      h1_vec.Streamer(R__b);
      h2_vec.Streamer(R__b);
      ipbst.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, b2ddsj_evt::IsA());
   } else {
      R__c = R__b.WriteVersion(b2ddsj_evt::IsA(), kTRUE);
      TObject::Streamer(R__b);
      info.Streamer(R__b);
      R__b << de;
      R__b << mbc;
      R__b << costhBcms;
      shape.Streamer(R__b);
      R__b << mode_b;
      R__b << mode_d;
      R__b << mode_ds;
      R__b << mode_dsj;
      R__b << flvb;
      R__b << md;
      R__b << mdsj;
      R__b << dmdst;
      R__b << mds;
      R__b << dmdsst;
      R__b << mvec;
      R__b.WriteArray(pvec, 3);
      R__b << cos_hel_dsj;
      R__b << cos_hel_vec;
      R__b << cos_hel_b;
      gam_dsj.Streamer(R__b);
      gam_dsst.Streamer(R__b);
      pi0_dst.Streamer(R__b);
      pi0_dsj.Streamer(R__b);
      pi_dst.Streamer(R__b);
      pip_dsj.Streamer(R__b);
      pim_dsj.Streamer(R__b);
      k_d.Streamer(R__b);
      pi_d.Streamer(R__b);
      pi2_d.Streamer(R__b);
      h_ds.Streamer(R__b);
      ks_ds.Streamer(R__b);
      h1_vec.Streamer(R__b);
      h2_vec.Streamer(R__b);
      ipbst.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void b2ddsj_evt::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class b2ddsj_evt.
      TClass *R__cl = ::b2ddsj_evt::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "info", &info);
      info.ShowMembers(R__insp, strcat(R__parent,"info.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "de", &de);
      R__insp.Inspect(R__cl, R__parent, "mbc", &mbc);
      R__insp.Inspect(R__cl, R__parent, "costhBcms", &costhBcms);
      R__insp.Inspect(R__cl, R__parent, "shape", &shape);
      shape.ShowMembers(R__insp, strcat(R__parent,"shape.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "mode_b", &mode_b);
      R__insp.Inspect(R__cl, R__parent, "mode_d", &mode_d);
      R__insp.Inspect(R__cl, R__parent, "mode_ds", &mode_ds);
      R__insp.Inspect(R__cl, R__parent, "mode_dsj", &mode_dsj);
      R__insp.Inspect(R__cl, R__parent, "flvb", &flvb);
      R__insp.Inspect(R__cl, R__parent, "md", &md);
      R__insp.Inspect(R__cl, R__parent, "mdsj", &mdsj);
      R__insp.Inspect(R__cl, R__parent, "dmdst", &dmdst);
      R__insp.Inspect(R__cl, R__parent, "mds", &mds);
      R__insp.Inspect(R__cl, R__parent, "dmdsst", &dmdsst);
      R__insp.Inspect(R__cl, R__parent, "mvec", &mvec);
      R__insp.Inspect(R__cl, R__parent, "pvec[3]", pvec);
      R__insp.Inspect(R__cl, R__parent, "cos_hel_dsj", &cos_hel_dsj);
      R__insp.Inspect(R__cl, R__parent, "cos_hel_vec", &cos_hel_vec);
      R__insp.Inspect(R__cl, R__parent, "cos_hel_b", &cos_hel_b);
      R__insp.Inspect(R__cl, R__parent, "gam_dsj", &gam_dsj);
      gam_dsj.ShowMembers(R__insp, strcat(R__parent,"gam_dsj.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "gam_dsst", &gam_dsst);
      gam_dsst.ShowMembers(R__insp, strcat(R__parent,"gam_dsst.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi0_dst", &pi0_dst);
      pi0_dst.ShowMembers(R__insp, strcat(R__parent,"pi0_dst.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi0_dsj", &pi0_dsj);
      pi0_dsj.ShowMembers(R__insp, strcat(R__parent,"pi0_dsj.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi_dst", &pi_dst);
      pi_dst.ShowMembers(R__insp, strcat(R__parent,"pi_dst.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pip_dsj", &pip_dsj);
      pip_dsj.ShowMembers(R__insp, strcat(R__parent,"pip_dsj.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pim_dsj", &pim_dsj);
      pim_dsj.ShowMembers(R__insp, strcat(R__parent,"pim_dsj.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "k_d", &k_d);
      k_d.ShowMembers(R__insp, strcat(R__parent,"k_d.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi_d", &pi_d);
      pi_d.ShowMembers(R__insp, strcat(R__parent,"pi_d.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi2_d", &pi2_d);
      pi2_d.ShowMembers(R__insp, strcat(R__parent,"pi2_d.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "h_ds", &h_ds);
      h_ds.ShowMembers(R__insp, strcat(R__parent,"h_ds.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "ks_ds", &ks_ds);
      ks_ds.ShowMembers(R__insp, strcat(R__parent,"ks_ds.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "h1_vec", &h1_vec);
      h1_vec.ShowMembers(R__insp, strcat(R__parent,"h1_vec.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "h2_vec", &h2_vec);
      h2_vec.ShowMembers(R__insp, strcat(R__parent,"h2_vec.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "ipbst", &ipbst);
      ipbst.ShowMembers(R__insp, strcat(R__parent,"ipbst.")); R__parent[R__ncp] = 0;
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_b2ddsj_evt(void *p) {
      return  p ? new(p) ::b2ddsj_evt : new ::b2ddsj_evt;
   }
   static void *newArray_b2ddsj_evt(Long_t nElements, void *p) {
      return p ? new(p) ::b2ddsj_evt[nElements] : new ::b2ddsj_evt[nElements];
   }
   // Wrapper around operator delete
   static void delete_b2ddsj_evt(void *p) {
      delete ((::b2ddsj_evt*)p);
   }
   static void deleteArray_b2ddsj_evt(void *p) {
      delete [] ((::b2ddsj_evt*)p);
   }
   static void destruct_b2ddsj_evt(void *p) {
      typedef ::b2ddsj_evt current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::b2ddsj_evt

//______________________________________________________________________________
void b2ddsj_mcevt::Streamer(TBuffer &R__b)
{
   // Stream an object of class b2ddsj_mcevt.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      genhep.Streamer(R__b);
      dsj_gen.Streamer(R__b);
      ds_gen.Streamer(R__b);
      d_gen.Streamer(R__b);
      b_gen.Streamer(R__b);
      gam_dsj_gen.Streamer(R__b);
      gam_dsst_gen.Streamer(R__b);
      pi0_dst_gen.Streamer(R__b);
      pi0_dsj_gen.Streamer(R__b);
      pi_dst_gen.Streamer(R__b);
      pip_dsj_gen.Streamer(R__b);
      pim_dsj_gen.Streamer(R__b);
      k_d_gen.Streamer(R__b);
      pi_d_gen.Streamer(R__b);
      pi2_d_gen.Streamer(R__b);
      h_ds_gen.Streamer(R__b);
      ks_ds_gen.Streamer(R__b);
      h1_vec_gen.Streamer(R__b);
      h2_vec_gen.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, b2ddsj_mcevt::IsA());
   } else {
      R__c = R__b.WriteVersion(b2ddsj_mcevt::IsA(), kTRUE);
      TObject::Streamer(R__b);
      genhep.Streamer(R__b);
      dsj_gen.Streamer(R__b);
      ds_gen.Streamer(R__b);
      d_gen.Streamer(R__b);
      b_gen.Streamer(R__b);
      gam_dsj_gen.Streamer(R__b);
      gam_dsst_gen.Streamer(R__b);
      pi0_dst_gen.Streamer(R__b);
      pi0_dsj_gen.Streamer(R__b);
      pi_dst_gen.Streamer(R__b);
      pip_dsj_gen.Streamer(R__b);
      pim_dsj_gen.Streamer(R__b);
      k_d_gen.Streamer(R__b);
      pi_d_gen.Streamer(R__b);
      pi2_d_gen.Streamer(R__b);
      h_ds_gen.Streamer(R__b);
      ks_ds_gen.Streamer(R__b);
      h1_vec_gen.Streamer(R__b);
      h2_vec_gen.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void b2ddsj_mcevt::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class b2ddsj_mcevt.
      TClass *R__cl = ::b2ddsj_mcevt::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "genhep", &genhep);
      genhep.ShowMembers(R__insp, strcat(R__parent,"genhep.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "dsj_gen", &dsj_gen);
      dsj_gen.ShowMembers(R__insp, strcat(R__parent,"dsj_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "ds_gen", &ds_gen);
      ds_gen.ShowMembers(R__insp, strcat(R__parent,"ds_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "d_gen", &d_gen);
      d_gen.ShowMembers(R__insp, strcat(R__parent,"d_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "b_gen", &b_gen);
      b_gen.ShowMembers(R__insp, strcat(R__parent,"b_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "gam_dsj_gen", &gam_dsj_gen);
      gam_dsj_gen.ShowMembers(R__insp, strcat(R__parent,"gam_dsj_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "gam_dsst_gen", &gam_dsst_gen);
      gam_dsst_gen.ShowMembers(R__insp, strcat(R__parent,"gam_dsst_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi0_dst_gen", &pi0_dst_gen);
      pi0_dst_gen.ShowMembers(R__insp, strcat(R__parent,"pi0_dst_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi0_dsj_gen", &pi0_dsj_gen);
      pi0_dsj_gen.ShowMembers(R__insp, strcat(R__parent,"pi0_dsj_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi_dst_gen", &pi_dst_gen);
      pi_dst_gen.ShowMembers(R__insp, strcat(R__parent,"pi_dst_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pip_dsj_gen", &pip_dsj_gen);
      pip_dsj_gen.ShowMembers(R__insp, strcat(R__parent,"pip_dsj_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pim_dsj_gen", &pim_dsj_gen);
      pim_dsj_gen.ShowMembers(R__insp, strcat(R__parent,"pim_dsj_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "k_d_gen", &k_d_gen);
      k_d_gen.ShowMembers(R__insp, strcat(R__parent,"k_d_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi_d_gen", &pi_d_gen);
      pi_d_gen.ShowMembers(R__insp, strcat(R__parent,"pi_d_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pi2_d_gen", &pi2_d_gen);
      pi2_d_gen.ShowMembers(R__insp, strcat(R__parent,"pi2_d_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "h_ds_gen", &h_ds_gen);
      h_ds_gen.ShowMembers(R__insp, strcat(R__parent,"h_ds_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "ks_ds_gen", &ks_ds_gen);
      ks_ds_gen.ShowMembers(R__insp, strcat(R__parent,"ks_ds_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "h1_vec_gen", &h1_vec_gen);
      h1_vec_gen.ShowMembers(R__insp, strcat(R__parent,"h1_vec_gen.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "h2_vec_gen", &h2_vec_gen);
      h2_vec_gen.ShowMembers(R__insp, strcat(R__parent,"h2_vec_gen.")); R__parent[R__ncp] = 0;
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_b2ddsj_mcevt(void *p) {
      return  p ? new(p) ::b2ddsj_mcevt : new ::b2ddsj_mcevt;
   }
   static void *newArray_b2ddsj_mcevt(Long_t nElements, void *p) {
      return p ? new(p) ::b2ddsj_mcevt[nElements] : new ::b2ddsj_mcevt[nElements];
   }
   // Wrapper around operator delete
   static void delete_b2ddsj_mcevt(void *p) {
      delete ((::b2ddsj_mcevt*)p);
   }
   static void deleteArray_b2ddsj_mcevt(void *p) {
      delete [] ((::b2ddsj_mcevt*)p);
   }
   static void destruct_b2ddsj_mcevt(void *p) {
      typedef ::b2ddsj_mcevt current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::b2ddsj_mcevt

/********************************************************
* b2ddsj_evt_dict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableb2ddsj_evt_dict();

extern "C" void G__set_cpp_environmentb2ddsj_evt_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("b2ddsj_evt.cc");
  G__add_compiledheader("b2ddsj_mcevt.cc");
  G__cpp_reset_tagtableb2ddsj_evt_dict();
}
#include <new>
extern "C" int G__cpp_dllrevb2ddsj_evt_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* b2ddsj_evt */
static int G__b2ddsj_evt_dict_162_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   b2ddsj_evt* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new b2ddsj_evt[n];
     } else {
       p = new((void*) gvp) b2ddsj_evt[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new b2ddsj_evt;
     } else {
       p = new((void*) gvp) b2ddsj_evt;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((b2ddsj_evt*) G__getstructoffset())->ClearEvt();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_evt*) G__getstructoffset())->DsjFl());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_evt*) G__getstructoffset())->DstFl());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_evt*) G__getstructoffset())->BchFl());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_evt*) G__getstructoffset())->DsstFl());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_evt*) G__getstructoffset())->DsjPi0Fl());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_evt*) G__getstructoffset())->DsjGammaFl());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const b2ddsj_evt*) G__getstructoffset())->Pvec());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const b2ddsj_evt*) G__getstructoffset())->ptvec());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const b2ddsj_evt*) G__getstructoffset())->costhvec());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) b2ddsj_evt::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) b2ddsj_evt::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) b2ddsj_evt::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      b2ddsj_evt::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((b2ddsj_evt*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) b2ddsj_evt::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) b2ddsj_evt::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) b2ddsj_evt::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_162_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) b2ddsj_evt::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__b2ddsj_evt_dict_162_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   b2ddsj_evt* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new b2ddsj_evt(*(b2ddsj_evt*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef b2ddsj_evt G__Tb2ddsj_evt;
static int G__b2ddsj_evt_dict_162_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (b2ddsj_evt*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((b2ddsj_evt*) (soff+(sizeof(b2ddsj_evt)*i)))->~G__Tb2ddsj_evt();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (b2ddsj_evt*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((b2ddsj_evt*) (soff))->~G__Tb2ddsj_evt();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__b2ddsj_evt_dict_162_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   b2ddsj_evt* dest = (b2ddsj_evt*) G__getstructoffset();
   *dest = *(b2ddsj_evt*) libp->para[0].ref;
   const b2ddsj_evt& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* b2ddsj_mcevt */
static int G__b2ddsj_evt_dict_163_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   b2ddsj_mcevt* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new b2ddsj_mcevt[n];
     } else {
       p = new((void*) gvp) b2ddsj_mcevt[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new b2ddsj_mcevt;
     } else {
       p = new((void*) gvp) b2ddsj_mcevt;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((b2ddsj_mcevt*) G__getstructoffset())->ClearEvt();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_mcevt*) G__getstructoffset())->Sig());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_mcevt*) G__getstructoffset())->Cmb());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const b2ddsj_mcevt*) G__getstructoffset())->Bkg());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) b2ddsj_mcevt::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) b2ddsj_mcevt::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) b2ddsj_mcevt::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      b2ddsj_mcevt::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((b2ddsj_mcevt*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) b2ddsj_mcevt::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) b2ddsj_mcevt::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) b2ddsj_mcevt::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__b2ddsj_evt_dict_163_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) b2ddsj_mcevt::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__b2ddsj_evt_dict_163_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   b2ddsj_mcevt* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new b2ddsj_mcevt(*(b2ddsj_mcevt*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef b2ddsj_mcevt G__Tb2ddsj_mcevt;
static int G__b2ddsj_evt_dict_163_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (b2ddsj_mcevt*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((b2ddsj_mcevt*) (soff+(sizeof(b2ddsj_mcevt)*i)))->~G__Tb2ddsj_mcevt();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (b2ddsj_mcevt*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((b2ddsj_mcevt*) (soff))->~G__Tb2ddsj_mcevt();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__b2ddsj_evt_dict_163_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   b2ddsj_mcevt* dest = (b2ddsj_mcevt*) G__getstructoffset();
   *dest = *(b2ddsj_mcevt*) libp->para[0].ref;
   const b2ddsj_mcevt& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* b2ddsj_evt */

/* b2ddsj_mcevt */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncb2ddsj_evt_dict {
 public:
  G__Sizep2memfuncb2ddsj_evt_dict(): p(&G__Sizep2memfuncb2ddsj_evt_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncb2ddsj_evt_dict::*p)();
};

size_t G__get_sizep2memfuncb2ddsj_evt_dict()
{
  G__Sizep2memfuncb2ddsj_evt_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceb2ddsj_evt_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt))) {
     b2ddsj_evt *G__Lderived;
     G__Lderived=(b2ddsj_evt*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt),G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt))) {
     b2ddsj_mcevt *G__Lderived;
     G__Lderived=(b2ddsj_mcevt*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt),G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableb2ddsj_evt_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* b2ddsj_evt */
static void G__setup_memvarb2ddsj_evt(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt));
   { b2ddsj_evt *p; p=(b2ddsj_evt*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->info)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_EvtInfo),-1,-1,1,"info=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->de)-(long)(p)),100,0,0,-1,-1,-1,1,"de=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mbc)-(long)(p)),100,0,0,-1,-1,-1,1,"mbc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->costhBcms)-(long)(p)),100,0,0,-1,-1,-1,1,"costhBcms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->shape)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_EvtShape),-1,-1,1,"shape=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mode_b)-(long)(p)),105,0,0,-1,-1,-1,1,"mode_b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mode_d)-(long)(p)),105,0,0,-1,-1,-1,1,"mode_d=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mode_ds)-(long)(p)),105,0,0,-1,-1,-1,1,"mode_ds=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mode_dsj)-(long)(p)),105,0,0,-1,-1,-1,1,"mode_dsj=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->flvb)-(long)(p)),105,0,0,-1,-1,-1,1,"flvb=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->md)-(long)(p)),100,0,0,-1,-1,-1,1,"md=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mdsj)-(long)(p)),100,0,0,-1,-1,-1,1,"mdsj=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dmdst)-(long)(p)),100,0,0,-1,-1,-1,1,"dmdst=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mds)-(long)(p)),100,0,0,-1,-1,-1,1,"mds=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dmdsst)-(long)(p)),100,0,0,-1,-1,-1,1,"dmdsst=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mvec)-(long)(p)),100,0,0,-1,-1,-1,1,"mvec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pvec)-(long)(p)),100,0,0,-1,-1,-1,1,"pvec[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cos_hel_dsj)-(long)(p)),100,0,0,-1,-1,-1,1,"cos_hel_dsj=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cos_hel_vec)-(long)(p)),100,0,0,-1,-1,-1,1,"cos_hel_vec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cos_hel_b)-(long)(p)),100,0,0,-1,-1,-1,1,"cos_hel_b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gam_dsj)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GammaInfo),-1,-1,1,"gam_dsj=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gam_dsst)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GammaInfo),-1,-1,1,"gam_dsst=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi0_dst)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_Pi0Info),-1,-1,1,"pi0_dst=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi0_dsj)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_Pi0Info),-1,-1,1,"pi0_dsj=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi_dst)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"pi_dst=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pip_dsj)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"pip_dsj=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pim_dsj)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"pim_dsj=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->k_d)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"k_d=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi_d)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"pi_d=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi2_d)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"pi2_d=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h_ds)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"h_ds=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ks_ds)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_Ks0Info),-1,-1,1,"ks_ds=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h1_vec)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"h1_vec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h2_vec)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TrackInfo),-1,-1,1,"h2_vec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ipbst)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_IPBoost),-1,-1,1,"ipbst=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* b2ddsj_mcevt */
static void G__setup_memvarb2ddsj_mcevt(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt));
   { b2ddsj_mcevt *p; p=(b2ddsj_mcevt*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->genhep)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenHepEvt),-1,-1,1,"genhep=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dsj_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"dsj_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ds_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"ds_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->d_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"d_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"b_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gam_dsj_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"gam_dsj_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gam_dsst_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"gam_dsst_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi0_dst_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"pi0_dst_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi0_dsj_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"pi0_dsj_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi_dst_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"pi_dst_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pip_dsj_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"pip_dsj_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pim_dsj_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"pim_dsj_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->k_d_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"k_d_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi_d_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"pi_d_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pi2_d_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"pi2_d_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h_ds_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"h_ds_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ks_ds_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"ks_ds_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h1_vec_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"h1_vec_gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h2_vec_gen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_GenParticleInfo),-1,-1,1,"h2_vec_gen=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarb2ddsj_evt_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncb2ddsj_evt(void) {
   /* b2ddsj_evt */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt));
   G__memfunc_setup("b2ddsj_evt",999,G__b2ddsj_evt_dict_162_0_1, 105, G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearEvt",790,G__b2ddsj_evt_dict_162_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DsjFl",467,G__b2ddsj_evt_dict_162_0_3, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DstFl",477,G__b2ddsj_evt_dict_162_0_4, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BchFl",447,G__b2ddsj_evt_dict_162_0_5, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DsstFl",592,G__b2ddsj_evt_dict_162_0_6, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DsjPi0Fl",700,G__b2ddsj_evt_dict_162_0_7, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DsjGammaFl",950,G__b2ddsj_evt_dict_162_0_8, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Pvec",398,G__b2ddsj_evt_dict_162_0_9, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ptvec",546,G__b2ddsj_evt_dict_162_0_10, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("costhvec",863,G__b2ddsj_evt_dict_162_0_11, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__b2ddsj_evt_dict_162_0_12, 85, G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&b2ddsj_evt::Class), 0);
   G__memfunc_setup("Class_Name",982,G__b2ddsj_evt_dict_162_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&b2ddsj_evt::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__b2ddsj_evt_dict_162_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&b2ddsj_evt::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__b2ddsj_evt_dict_162_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&b2ddsj_evt::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__b2ddsj_evt_dict_162_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__b2ddsj_evt_dict_162_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&b2ddsj_evt::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__b2ddsj_evt_dict_162_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&b2ddsj_evt::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__b2ddsj_evt_dict_162_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&b2ddsj_evt::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__b2ddsj_evt_dict_162_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&b2ddsj_evt::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("b2ddsj_evt", 999, G__b2ddsj_evt_dict_162_0_24, (int) ('i'), G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt), -1, 0, 1, 1, 1, 0, "u 'b2ddsj_evt' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~b2ddsj_evt", 1125, G__b2ddsj_evt_dict_162_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__b2ddsj_evt_dict_162_0_26, (int) ('u'), G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt), -1, 1, 1, 1, 1, 0, "u 'b2ddsj_evt' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncb2ddsj_mcevt(void) {
   /* b2ddsj_mcevt */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt));
   G__memfunc_setup("b2ddsj_mcevt",1207,G__b2ddsj_evt_dict_163_0_1, 105, G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearEvt",790,G__b2ddsj_evt_dict_163_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Sig",291,G__b2ddsj_evt_dict_163_0_3, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cmb",274,G__b2ddsj_evt_dict_163_0_4, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Bkg",276,G__b2ddsj_evt_dict_163_0_5, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__b2ddsj_evt_dict_163_0_6, 85, G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&b2ddsj_mcevt::Class), 0);
   G__memfunc_setup("Class_Name",982,G__b2ddsj_evt_dict_163_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&b2ddsj_mcevt::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__b2ddsj_evt_dict_163_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&b2ddsj_mcevt::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__b2ddsj_evt_dict_163_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&b2ddsj_mcevt::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__b2ddsj_evt_dict_163_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__b2ddsj_evt_dict_163_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&b2ddsj_mcevt::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__b2ddsj_evt_dict_163_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&b2ddsj_mcevt::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__b2ddsj_evt_dict_163_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&b2ddsj_mcevt::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__b2ddsj_evt_dict_163_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&b2ddsj_mcevt::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("b2ddsj_mcevt", 1207, G__b2ddsj_evt_dict_163_0_18, (int) ('i'), G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt), -1, 0, 1, 1, 1, 0, "u 'b2ddsj_mcevt' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~b2ddsj_mcevt", 1333, G__b2ddsj_evt_dict_163_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__b2ddsj_evt_dict_163_0_20, (int) ('u'), G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt), -1, 1, 1, 1, 1, 0, "u 'b2ddsj_mcevt' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncb2ddsj_evt_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalb2ddsj_evt_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcb2ddsj_evt_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__b2ddsj_evt_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_EvtInfo = { "EvtInfo" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_EvtShape = { "EvtShape" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_GammaInfo = { "GammaInfo" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_GenHepEvt = { "GenHepEvt" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_GenParticleInfo = { "GenParticleInfo" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_IPBoost = { "IPBoost" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_Ks0Info = { "Ks0Info" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_Pi0Info = { "Pi0Info" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_TrackInfo = { "TrackInfo" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_b2ddsj_evt = { "b2ddsj_evt" , 99 , -1 };
G__linked_taginfo G__b2ddsj_evt_dictLN_b2ddsj_mcevt = { "b2ddsj_mcevt" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableb2ddsj_evt_dict() {
  G__b2ddsj_evt_dictLN_TClass.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_TBuffer.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_TMemberInspector.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_TObject.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_EvtInfo.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_EvtShape.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_GammaInfo.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_GenHepEvt.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_GenParticleInfo.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_IPBoost.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_Ks0Info.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_Pi0Info.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_TrackInfo.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_b2ddsj_evt.tagnum = -1 ;
  G__b2ddsj_evt_dictLN_b2ddsj_mcevt.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableb2ddsj_evt_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_EvtInfo);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_EvtShape);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_GammaInfo);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_GenHepEvt);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_GenParticleInfo);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_IPBoost);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_Ks0Info);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_Pi0Info);
   G__get_linked_tagnum_fwd(&G__b2ddsj_evt_dictLN_TrackInfo);
   G__tagtable_setup(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_evt),sizeof(b2ddsj_evt),-1,28928,(char*)NULL,G__setup_memvarb2ddsj_evt,G__setup_memfuncb2ddsj_evt);
   G__tagtable_setup(G__get_linked_tagnum(&G__b2ddsj_evt_dictLN_b2ddsj_mcevt),sizeof(b2ddsj_mcevt),-1,28928,(char*)NULL,G__setup_memvarb2ddsj_mcevt,G__setup_memfuncb2ddsj_mcevt);
}
extern "C" void G__cpp_setupb2ddsj_evt_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupb2ddsj_evt_dict()");
  G__set_cpp_environmentb2ddsj_evt_dict();
  G__cpp_setup_tagtableb2ddsj_evt_dict();

  G__cpp_setup_inheritanceb2ddsj_evt_dict();

  G__cpp_setup_typetableb2ddsj_evt_dict();

  G__cpp_setup_memvarb2ddsj_evt_dict();

  G__cpp_setup_memfuncb2ddsj_evt_dict();
  G__cpp_setup_globalb2ddsj_evt_dict();
  G__cpp_setup_funcb2ddsj_evt_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncb2ddsj_evt_dict();
  return;
}
class G__cpp_setup_initb2ddsj_evt_dict {
  public:
    G__cpp_setup_initb2ddsj_evt_dict() { G__add_setup_func("b2ddsj_evt_dict",(G__incsetup)(&G__cpp_setupb2ddsj_evt_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initb2ddsj_evt_dict() { G__remove_setup_func("b2ddsj_evt_dict"); }
};
G__cpp_setup_initb2ddsj_evt_dict G__cpp_setup_initializerb2ddsj_evt_dict;

